In [1]:
### Step 1a: Install Dependencies
import sys, os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import ast
import openpyxl
from openpyxl.utils import get_column_letter, quote_sheetname
from openpyxl.styles import Alignment, Font, Border, Side, PatternFill

In [2]:
# Step 1: Load the two dataframes
# Replace with your actual file paths or data sources
elements_26_df = pd.read_csv(r"data\Alma_Galter_Users_Match\2025_06-10 elements_25_df.csv")  # This contains the 'NetID' column
df2 = pd.read_csv(r"data\Alma_Galter_Users_Match\2025_07-08_Galter_User_Details.csv")  # This contains the 'Primary Identifier' column

C:\Users\keg827\AppData\Local\Temp\ipykernel_7532\3231488105.py:3: DtypeWarning: Columns (5,39,40,44,45,49,50,54,55,56,57,65,68,87) have mixed types. Specify dtype option on import or set low_memory=False.
  elements_26_df = pd.read_csv(r"data\Alma_Galter_Users_Match\2025_06-10 elements_25_df.csv")  # This contains the 'NetID' column

## Data Cleaning Section

Using **Report 25** and functions from the `ORCID_Data_Analysis_Quarterly_Report` module to clean the data.

This step includes:
- Standardizing NetIDs
- Removing duplicates
- Matching and merging with external data sources

**Source File:** 2025_06-10 elements_25_df.csv  
**Functions Used From:** `https://github.com/galterlibrarymetricscore/NU_ORCID_Review_Reports`

In [3]:
### Step 1b: Define global variables 

# year = "2024"
# month = "09"
# month_name = "September"
# day = "13"

# year = "2024"
# month = "06"
# month_name = "June"
# day = "12"

# year = "2024"
# month = "03"
# month_name = "March"
# day = "04"

# year = "2024"
# month = "12"
# month_name = "December"
# day = "05"

# year = "2025"
# month = "02"
# month_name = "February"
# day = "07"

# year = "2025"
# month = "03"
# month_name = "March"
# day = "04"

# year = "2025"
# month = "04"
# month_name = "April"
# day = "09"

# year = "2025"
# month = "05"
# month_name = "May"
# day = "15"

year = "2025"
month = "06"
month_name = "June"
day = "10"

### Step 1c: Define a function to save DataFrames as csv files
def save_dataframe(description, dataframe):
    folder_path = f"output/Alma_Galter_Users_Match/{year}_{month} {month_name}"
    file_name = f"{year}_{month}-{day} {description}.csv"
    
    # Save the DataFrame to a CSV file without extra newlines
    dataframe.to_csv(f"{folder_path}/{file_name}", index=False)
        
### Step 1d: Define a function to save DataFrames as pickle files
def save_dataframe_pickle(description, dataframe):
    folder_path = f"output/Alma_Galter_Users_Match/{year}_{month} {month_name}"
    file_name = f"{year}_{month}-{day} {description}.pkl"
    
    # Save the DataFrame as a pickle file
    dataframe.to_pickle(f"{folder_path}/{file_name}")

### Step 1e: Define a function to load DataFrames from csv files
def load_dataframe(description):
    folder_path = f"output/Alma_Galter_Users_Match/{year}_{month} {month_name}"
    file_name = f"{year}_{month}-{day} {description}.csv"
    
    # Load the DataFrame from the CSV file
    dataframe = pd.read_csv(f"{folder_path}/{file_name}")
    return dataframe
    
# Step 1f: Define a function to load DataFrames from pickle files
def load_dataframe_pickle(description):
    folder_path = f"output/Alma_Galter_Users_Match/{year}_{month} {month_name}"
    file_name = f"{year}_{month}-{day} {description}.pkl"
    
    # Load the DataFrame from the pickle file
    dataframe = pd.read_pickle(f"{folder_path}/{file_name}")
    return dataframe

In [4]:
## Step 50: Function to check if data is present in the column
def check_ORCID_at_NU_present(value):
    if pd.isna(value) or value == '':
        return 'N'
    else:
        return 'Y'

# Apply the function to create a new column
elements_26_df['Completed Connection between ORCID and NetID?'] = elements_26_df['ORCID'].apply(lambda x: check_ORCID_at_NU_present(x))

In [5]:
# Step 51: Function to check if ORCID data is present in the column
def check_name_match_at_ORCID_present(value):
    if pd.isna(value) or value == '':
        return 'N'
    else:
        return 'Y'

# Apply the function to create a new column
elements_26_df['Possible name match at ORCID.org?'] = elements_26_df['Name Match at ORCID.org?'].apply(lambda x: check_name_match_at_ORCID_present(x))

In [8]:
## Save the dataframe

# Create variable for dataframe
description = "elements_26_df" 

# Call the save function
save_dataframe(description, elements_26_df)

In [9]:
#  Print the column indices and column names
print("Column indices and names:")
for index, column_name in enumerate(elements_26_df.columns):
    print("Index:", index, "| Column Name:", column_name)

Column indices and names:
Index: 0 | Column Name: Name_x
Index: 1 | Column Name: Position
Index: 2 | Column Name: Department_School
Index: 3 | Column Name: Department
Index: 4 | Column Name: School
Index: 5 | Column Name: Employee ID
Index: 6 | Column Name: NetID
Index: 7 | Column Name: Is Current Employee 1=Yes, 0=No
Index: 8 | Column Name: Is Academic Employee 1=Yes, 0=No
Index: 9 | Column Name: Arrive Date
Index: 10 | Column Name: Leave Date
Index: 11 | Column Name: Email
Index: 12 | Column Name: Department_ID_Descriptor_1
Index: 13 | Column Name: Department_Class_Descriptor_1
Index: 14 | Column Name: Department_ID_Group_Descriptor_1
Index: 15 | Column Name: Position_Type_Descriptor_1
Index: 16 | Column Name: Position_Category_Descriptor_1
Index: 17 | Column Name: Department_ID_Descriptor_2
Index: 18 | Column Name: Department_Class_Descriptor_2
Index: 19 | Column Name: Department_ID_Group_Descriptor_2
Index: 20 | Column Name: Position_Type_Descriptor_2
Index: 21 | Column Name: Position_Category_Descriptor_2
Index: 22 | Column Name: Department_ID_Descriptor_3
Index: 23 | Column Name: Department_Class_Descriptor_3
Index: 24 | Column Name: Department_ID_Group_Descriptor_3
Index: 25 | Column Name: Position_Type_Descriptor_3
Index: 26 | Column Name: Position_Category_Descriptor_3
Index: 27 | Column Name: Department_ID_Descriptor_4
Index: 28 | Column Name: Department_Class_Descriptor_4
Index: 29 | Column Name: Department_ID_Group_Descriptor_4
Index: 30 | Column Name: Position_Type_Descriptor_4
Index: 31 | Column Name: Position_Category_Descriptor_4
Index: 32 | Column Name: Department_ID_Descriptor_5
Index: 33 | Column Name: Department_Class_Descriptor_5
Index: 34 | Column Name: Department_ID_Group_Descriptor_5
Index: 35 | Column Name: Position_Type_Descriptor_5
Index: 36 | Column Name: Position_Category_Descriptor_5
Index: 37 | Column Name: Department_ID_Descriptor_6
Index: 38 | Column Name: Department_Class_Descriptor_6
Index: 39 | Column Name: Department_ID_Group_Descriptor_6
Index: 40 | Column Name: Position_Type_Descriptor_6
Index: 41 | Column Name: Position_Category_Descriptor_6
Index: 42 | Column Name: Department_ID_Descriptor_7
Index: 43 | Column Name: Department_Class_Descriptor_7
Index: 44 | Column Name: Department_ID_Group_Descriptor_7
Index: 45 | Column Name: Position_Type_Descriptor_7
Index: 46 | Column Name: Position_Category_Descriptor_7
Index: 47 | Column Name: Department_ID_Descriptor_8
Index: 48 | Column Name: Department_Class_Descriptor_8
Index: 49 | Column Name: Department_ID_Group_Descriptor_8
Index: 50 | Column Name: Position_Type_Descriptor_8
Index: 51 | Column Name: Position_Category_Descriptor_8
Index: 52 | Column Name: Department_ID_Descriptor_9
Index: 53 | Column Name: Department_Class_Descriptor_9
Index: 54 | Column Name: Department_ID_Group_Descriptor_9
Index: 55 | Column Name: Position_Type_Descriptor_9
Index: 56 | Column Name: Department_ID_Descriptor_10
Index: 57 | Column Name: Department_Class_Descriptor_10
Index: 58 | Column Name: Department_ID_Group_Descriptor_10
Index: 59 | Column Name: Position_Type_Descriptor_10
Index: 60 | Column Name: Position_Category_Descriptor_10
Index: 61 | Column Name: Position_Category_Descriptor_9
Index: 62 | Column Name: Completed Connection between ORCID and Northwestern Elements?
Index: 63 | Column Name: Write access enabled between ORCID and Northwestern Elements?
Index: 64 | Column Name: Date/Time Connection edited between ORCID And Northwestern Elements
Index: 65 | Column Name: Confirmed Web of Science ResearcherID from Northwestern Elements
Index: 66 | Column Name: Confirmed ORCID from Northwestern Elements
Index: 67 | Column Name: Confirmed Scopus AuthorID from Northwestern Elements
Index: 68 | Column Name: Confirmed Corresponding Email Address from Northwestern Elements
Index: 69 | Column Name: Possible name match at Web of Science ResearcherID from Northwestern Elements
Index: 70 | Column Name: Possible name match at ORCID from Northwestern Elements
Index: 71 | Column Name: Possible name match at Scopus AuthorID from Northwestern Elements
Index: 72 | Column Name: Possible email match from Corresponding Email Addresses from Northwestern Elements
Index: 73 | Column Name: Possible name match at SSRN AuthorID from Northwestern Elements
Index: 74 | Column Name: Retiree or Emeritus?
Index: 75 | Column Name: Department_New
Index: 76 | Column Name: School_New
Index: 77 | Column Name: School_All
Index: 78 | Column Name: Department_All
Index: 79 | Column Name: Name_Processed
Index: 80 | Column Name: School_Indiv
Index: 81 | Column Name: Department_Indiv
Index: 82 | Column Name: Can be found on more than one school?
Index: 83 | Column Name: Can be found on more than one department?
Index: 84 | Column Name: Faculty or Staff
Index: 85 | Column Name: ORCID
Index: 86 | Column Name: Name_y
Index: 87 | Column Name: Unnamed: 3
Index: 88 | Column Name: _merge
Index: 89 | Column Name: Sponsored Research since 2021?
Index: 90 | Column Name: Name Match at ORCID.org?
Index: 91 | Column Name: Completed Connection between ORCID and NetID?
Index: 92 | Column Name: Possible name match at ORCID.org?

In [10]:
# Step 52: Deleting multiple columns without modifying the original DataFrame

columns_to_drop = [#'Unnamed: 0.1',
                    #'Unnamed: 0.2',
                   # 'Unnamed: 0',
                    'Unnamed: 3',
                    'Name_y',
                    'Department_School',
                    'Department',
                    #'Department_New_x',
                    'School',
                    #'School_x',
                    #'School_New_x',
                    #'School_y',
                    'Employee ID',
                    'Is Current Employee 1=Yes, 0=No',
                    'Is Academic Employee 1=Yes, 0=No',
                    'Arrive Date',
                    #'Leave Date',
                    'Department_ID_Descriptor_1',
                    'Department_Class_Descriptor_1',
                    'Department_ID_Group_Descriptor_1',
                    'Position_Type_Descriptor_1',
                    'Position_Category_Descriptor_1',
                    'Department_ID_Descriptor_2',
                    'Department_Class_Descriptor_2',
                    'Department_ID_Group_Descriptor_2',
                    'Position_Type_Descriptor_2',
                    'Position_Category_Descriptor_2',
                    'Department_ID_Descriptor_3',
                    'Department_Class_Descriptor_3',
                    'Department_ID_Group_Descriptor_3',
                    'Position_Type_Descriptor_3',
                    'Position_Category_Descriptor_3',
                    'Department_ID_Descriptor_4',
                    'Department_Class_Descriptor_4',
                    'Department_ID_Group_Descriptor_4',
                    'Position_Type_Descriptor_4',
                    'Position_Category_Descriptor_4',
                    'Department_ID_Descriptor_5',
                    'Department_Class_Descriptor_5',
                    'Department_ID_Group_Descriptor_5',
                    'Position_Type_Descriptor_5',
                    'Position_Category_Descriptor_5',
                    'Department_ID_Descriptor_6',
                    'Department_Class_Descriptor_6',
                    'Department_ID_Group_Descriptor_6',
                    'Position_Type_Descriptor_6',
                    'Position_Category_Descriptor_6',
                    'Department_ID_Descriptor_7',
                    'Department_Class_Descriptor_7',
                    'Department_ID_Group_Descriptor_7',
                    'Position_Type_Descriptor_7',
                    'Position_Category_Descriptor_7',
                    'Department_ID_Descriptor_8',
                    'Department_Class_Descriptor_8',
                    'Department_ID_Group_Descriptor_8',
                    'Position_Type_Descriptor_8',
                    'Position_Category_Descriptor_8',
                    'Department_ID_Descriptor_9',
                    'Department_Class_Descriptor_9',
                    'Department_ID_Group_Descriptor_9',
                    'Position_Type_Descriptor_9',
                    'Position_Category_Descriptor_9',
                    'Department_ID_Descriptor_10',
                    'Department_Class_Descriptor_10',
                    'Department_ID_Group_Descriptor_10',
                    'Position_Type_Descriptor_10',
                    'Position_Category_Descriptor_10',
                    'Completed Connection between ORCID and Northwestern Elements?',
                    #'Write access enabled between ORCID and Northwestern Elements?',
                    #'Broken Connection between ORCID and Northwestern Elements?', Not for March 2024 or June 2024
                    'Date/Time Connection edited between ORCID And Northwestern Elements',
                    'Confirmed Web of Science ResearcherID from Northwestern Elements',
                    'Confirmed Scopus AuthorID from Northwestern Elements',
                    'Confirmed Corresponding Email Address from Northwestern Elements',
                    'Possible name match at Web of Science ResearcherID from Northwestern Elements',
                    'Possible name match at Scopus AuthorID from Northwestern Elements',
                    'Possible email match from Corresponding Email Addresses from Northwestern Elements',
                    'Possible name match at SSRN AuthorID from Northwestern Elements',
                    
                    'Possible name match at ORCID.org?',
                    #'School_All',
                    #'Department_All',
                    #'Department_New',
                   # 'School_New',
                   'Name_Processed',
                    'Name_y',
                   '_merge'
                   


]
def drop_columns(elements_df, columns_to_drop):
    """
    Drop specified columns from the elements DataFrame.

    Args:
    - elements_df (pandas DataFrame): The DataFrame containing elements data.
    - columns_to_drop (list): List of column names to drop from the DataFrame.

    Returns:
    - pandas DataFrame: The DataFrame with specified columns dropped.
    """
    # Drop the specified columns
    filtered_elements_df = elements_df.drop(columns=columns_to_drop, inplace=False)

    return filtered_elements_df

# Call the function
elements_27_df = drop_columns(elements_26_df, columns_to_drop)
elements_27_df.head()

,Name_x,Position,NetID,Leave Date,Email,Write access enabled between ORCID and Northwestern Elements?,Confirmed ORCID from Northwestern Elements,Possible name match at ORCID from Northwestern Elements,Retiree or Emeritus?,Department_New,...,Department_All,School_Indiv,Department_Indiv,Can be found on more than one school?,Can be found on more than one department?,Faculty or Staff,ORCID,Sponsored Research since 2021?,Name Match at ORCID.org?,Completed Connection between ORCID and NetID?
0,Piotr Hebal,Developer Senior,phb010,10/19/2018,hrisdevelopment@northwestern.edu,N,NaN,NaN,N,Galter Health Science Library,...,['Galter Health Science Library'],Feinberg School of Medicine,Galter Health Science Library,N,N,Staff,NaN,N,NaN,N
1,Violeta Ilik,"Department Head, Library",viq454,7/21/2017,violeta.ilik@northwestern.edu,N,NaN,0000-0003-2588-3084,N,Galter Health Science Library,...,['Galter Health Science Library'],Feinberg School of Medicine,Galter Health Science Library,N,N,Librarian Faculty,NaN,N,NaN,N
2,William White,Professor,wjw412,NaN,white@northwestern.edu,N,NaN,NaN,N,Industrial Engineering and Management Sciences,...,"['Ind/EnggMgmt Sci', 'MEDS and Opns', 'Ind/Eng...",Robert R. McCormick School of Engineering and ...,Industrial Engineering and Management Sciences,Y,Y,Faculty,NaN,N,NaN,N
3,William White,Professor,wjw412,NaN,white@northwestern.edu,N,NaN,NaN,N,Industrial Engineering and Management Sciences,...,"['Ind/EnggMgmt Sci', 'MEDS and Opns', 'Ind/Eng...",J. L. Kellogg School of Management,Managerial Economics and Decision Sciences,Y,Y,Faculty,NaN,N,NaN,N
4,Jon Lomasney,Associate Professor,jlomas,NaN,j-lomasney@northwestern.edu,N,NaN,0000-0002-0438-2427,N,Pathology,...,"['Pathology', 'Pharmacology', 'Pathology', 'Pa...",Feinberg School of Medicine,Pathology,N,Y,Faculty,NaN,Y,NaN,N

In [11]:
## Save the dataframe

# Create variable for dataframe
description = "elements_27_df" 

# Call the save function
save_dataframe(description, elements_27_df)

In [12]:
#  Print the column indices and column names
print("Column indices and names:")
for index, column_name in enumerate(elements_27_df.columns):
    print("Index:", index, "| Column Name:", column_name)

Column indices and names:
Index: 0 | Column Name: Name_x
Index: 1 | Column Name: Position
Index: 2 | Column Name: NetID
Index: 3 | Column Name: Leave Date
Index: 4 | Column Name: Email
Index: 5 | Column Name: Write access enabled between ORCID and Northwestern Elements?
Index: 6 | Column Name: Confirmed ORCID from Northwestern Elements
Index: 7 | Column Name: Possible name match at ORCID from Northwestern Elements
Index: 8 | Column Name: Retiree or Emeritus?
Index: 9 | Column Name: Department_New
Index: 10 | Column Name: School_New
Index: 11 | Column Name: School_All
Index: 12 | Column Name: Department_All
Index: 13 | Column Name: School_Indiv
Index: 14 | Column Name: Department_Indiv
Index: 15 | Column Name: Can be found on more than one school?
Index: 16 | Column Name: Can be found on more than one department?
Index: 17 | Column Name: Faculty or Staff
Index: 18 | Column Name: ORCID
Index: 19 | Column Name: Sponsored Research since 2021?
Index: 20 | Column Name: Name Match at ORCID.org?
Index: 21 | Column Name: Completed Connection between ORCID and NetID?

In [13]:
# Step 53: Renaming columns without modifying the original DataFrame
def rename_columns(elements_df, columns_to_rename):
    """
    Rename specified columns in the elements DataFrame without modifying the original DataFrame.

    Args:
    - elements_df (pandas DataFrame): The DataFrame containing elements data.
    - columns_to_rename (dict): A dictionary where keys are the current column names and values are the desired column names.

    Returns:
    - pandas DataFrame: The DataFrame with specified columns renamed.
    """
    # Rename the specified columns
    renamed_elements_df = elements_df.rename(columns=columns_to_rename, inplace=False)

    return renamed_elements_df

# Specify the columns to rename
## This means we will want school_x (primary appointment), school_new_y (as school), and department_new_y (as department)
columns_to_rename = {
    'Name_x': 'Full Name', 
    'School_New': 'School (primary appointment)',
    'Department_New': 'Department (primary appointment)', 
    'School_Indiv': 'School (academic appointment)',
    'Department_Indiv': 'Department (academic appointment)',
    'Leave Date': 'Leave Date (if no longer at NU)',
    'Sponsored Research since 2021?': 'NIH-specific Funded Research since 2021?',
    'Name Match at ORCID.org?': 'Possible name match from ORCID.org',
    'ORCID': 'Confirmed ORCID from orcid.it.northwestern',
    'Write access enabled between ORCID and Northwestern Elements?':'Completed Connection between ORCID and Northwestern Elements (with write access enabled)?'
}

# Call the function
elements_28_df = rename_columns(elements_27_df, columns_to_rename)

In [14]:
## Save CSV of dataframe

# Create variable for dataframe
description = "elements_28_df" 

# Call the save function
save_dataframe(description, elements_28_df)

In [15]:
#  Print the column indices and column names
print("Column indices and names:")
for index, column_name in enumerate(elements_28_df.columns):
    print("Index:", index, "| Column Name:", column_name)

Column indices and names:
Index: 0 | Column Name: Full Name
Index: 1 | Column Name: Position
Index: 2 | Column Name: NetID
Index: 3 | Column Name: Leave Date (if no longer at NU)
Index: 4 | Column Name: Email
Index: 5 | Column Name: Completed Connection between ORCID and Northwestern Elements (with write access enabled)?
Index: 6 | Column Name: Confirmed ORCID from Northwestern Elements
Index: 7 | Column Name: Possible name match at ORCID from Northwestern Elements
Index: 8 | Column Name: Retiree or Emeritus?
Index: 9 | Column Name: Department (primary appointment)
Index: 10 | Column Name: School (primary appointment)
Index: 11 | Column Name: School_All
Index: 12 | Column Name: Department_All
Index: 13 | Column Name: School (academic appointment)
Index: 14 | Column Name: Department (academic appointment)
Index: 15 | Column Name: Can be found on more than one school?
Index: 16 | Column Name: Can be found on more than one department?
Index: 17 | Column Name: Faculty or Staff
Index: 18 | Column Name: Confirmed ORCID from orcid.it.northwestern
Index: 19 | Column Name: NIH-specific Funded Research since 2021?
Index: 20 | Column Name: Possible name match from ORCID.org
Index: 21 | Column Name: Completed Connection between ORCID and NetID?

In [16]:
## Step 54:  Reorder columns by creating a new DataFrame
def reorder_columns(elements_df, column_order):
    """
    Reorder columns in the elements DataFrame by creating a new DataFrame.

    Args:
    - elements_df (pandas DataFrame): The DataFrame containing elements data.
    - column_order (list): A list specifying the desired order of columns.

    Returns:
    - pandas DataFrame: The DataFrame with columns reordered.
    """
    # Reorder columns based on the specified column order
    reordered_elements_df = elements_df[column_order]

    return reordered_elements_df

# Specify the desired order of columns
column_order = ['Full Name',
                'Position',
                'Faculty or Staff',
                'NetID',
                'Email',
                'Department (academic appointment)',
                'School (academic appointment)',
                'Leave Date (if no longer at NU)',
                'Department (primary appointment)',
                'School (primary appointment)',
                'Can be found on more than one school?',
                'School_All',
                'Can be found on more than one department?',
                'Department_All',
                'NIH-specific Funded Research since 2021?',
                'Completed Connection between ORCID and NetID?',
                'Confirmed ORCID from orcid.it.northwestern',
                'Completed Connection between ORCID and Northwestern Elements (with write access enabled)?',
                'Confirmed ORCID from Northwestern Elements',
                'Possible name match from ORCID.org',
                'Possible name match at ORCID from Northwestern Elements']

# Call the function
elements_29_df = reorder_columns(elements_28_df, column_order)
elements_29_df.head()

,Full Name,Position,Faculty or Staff,NetID,Email,Department (academic appointment),School (academic appointment),Leave Date (if no longer at NU),Department (primary appointment),School (primary appointment),...,School_All,Can be found on more than one department?,Department_All,NIH-specific Funded Research since 2021?,Completed Connection between ORCID and NetID?,Confirmed ORCID from orcid.it.northwestern,Completed Connection between ORCID and Northwestern Elements (with write access enabled)?,Confirmed ORCID from Northwestern Elements,Possible name match from ORCID.org,Possible name match at ORCID from Northwestern Elements
0,Piotr Hebal,Developer Senior,Staff,phb010,hrisdevelopment@northwestern.edu,Galter Health Science Library,Feinberg School of Medicine,10/19/2018,Galter Health Science Library,Feinberg School of Medicine,...,['Feinberg School of Medicine'],N,['Galter Health Science Library'],N,N,NaN,N,NaN,NaN,NaN
1,Violeta Ilik,"Department Head, Library",Librarian Faculty,viq454,violeta.ilik@northwestern.edu,Galter Health Science Library,Feinberg School of Medicine,7/21/2017,Galter Health Science Library,Feinberg School of Medicine,...,['Feinberg School of Medicine'],N,['Galter Health Science Library'],N,N,NaN,N,NaN,NaN,0000-0003-2588-3084
2,William White,Professor,Faculty,wjw412,white@northwestern.edu,Industrial Engineering and Management Sciences,Robert R. McCormick School of Engineering and ...,NaN,Industrial Engineering and Management Sciences,Robert R. McCormick School of Engineering and ...,...,['Robert R. McCormick School of Engineering an...,Y,"['Ind/EnggMgmt Sci', 'MEDS and Opns', 'Ind/Eng...",N,N,NaN,N,NaN,NaN,NaN
3,William White,Professor,Faculty,wjw412,white@northwestern.edu,Managerial Economics and Decision Sciences,J. L. Kellogg School of Management,NaN,Industrial Engineering and Management Sciences,Robert R. McCormick School of Engineering and ...,...,['Robert R. McCormick School of Engineering an...,Y,"['Ind/EnggMgmt Sci', 'MEDS and Opns', 'Ind/Eng...",N,N,NaN,N,NaN,NaN,NaN
4,Jon Lomasney,Associate Professor,Faculty,jlomas,j-lomasney@northwestern.edu,Pathology,Feinberg School of Medicine,NaN,Pathology,Feinberg School of Medicine,...,"['Feinberg School of Medicine', 'Feinberg Scho...",Y,"['Pathology', 'Pharmacology', 'Pathology', 'Pa...",Y,N,NaN,N,NaN,NaN,0000-0002-0438-2427

In [17]:
## Save CSV of dataframe

# Create variable for dataframe
description = "elements_29_df" 

# Call the save function
save_dataframe(description, elements_29_df)

In [18]:
## Step 1b: Remove duplicates for multiple schools

elements_29_df = elements_29_df.drop_duplicates(subset='NetID', keep='first')

## Custom Processing for this report process

This section uses functions written specifically for this report to:
- Drop duplicates for multi-affiliated individuals
- Merge Alma and Elements datasets
- Export to Excel

In [19]:
# Step 2: Merge the dataframes on 'NetID' and 'Primary Identifier'
merged_df = pd.merge(elements_29_df, df2, left_on='NetID', right_on='Primary Identifier', how='inner')
merged_df.head()

,Full Name_x,Position,Faculty or Staff,NetID,Email,Department (academic appointment),School (academic appointment),Leave Date (if no longer at NU),Department (primary appointment),School (primary appointment),...,Possible name match at ORCID from Northwestern Elements,User Group,Last Activity Date,Job Description,Is Blocked,Full Name_y,Expiry Date,Primary Identifier,Job Category,Campus Name
0,Jon Lomasney,Associate Professor,Faculty,jlomas,j-lomasney@northwestern.edu,Pathology,Feinberg School of Medicine,NaN,Pathology,Feinberg School of Medicine,...,0000-0002-0438-2427,Health Sci. Faculty,NaN,NaN,No,Lomasney Jon,6/30/2026,jlomas,NaN,NaN
1,William Myers,Assistant Professor,Faculty,wmyers,wmyers@northwestern.edu,Ophthalmology,Feinberg School of Medicine,NaN,Ophthalmology,Feinberg School of Medicine,...,0000-0001-7873-861X,Health Sci. Faculty,NaN,NaN,No,Myers William,6/30/2026,wmyers,NaN,NaN
2,Barry Levine,"Instructor, Clinical",Faculty,bml896,b-levine@northwestern.edu,"Medicine, General Internal Medicine Division",Feinberg School of Medicine,NaN,"Medicine, General Internal Medicine Division",Feinberg School of Medicine,...,NaN,Health Sci. Faculty,NaN,NaN,No,Levine Barry,6/30/2026,bml896,NaN,NaN
3,Todd Parrish,Professor,Faculty,tbp688,toddp@northwestern.edu,Radiology,Feinberg School of Medicine,NaN,Radiology,Feinberg School of Medicine,...,0000-0002-1184-1572,Health Sci. Faculty,11/2/2023,NaN,No,Parrish Todd,6/30/2026,tbp688,NaN,NaN
4,Bronwyn Rae,Lecturer,Faculty,brr666,brae@northwestern.edu,Preventive Medicine,Feinberg School of Medicine,NaN,Preventive Medicine,Feinberg School of Medicine,...,NaN,Health Sci. Faculty,5/14/2024,NaN,No,Rae Bronwyn,6/30/2026,brr666,NaN,NaN

In [20]:
# Step 3: Identify unmatched rows from df2 (those that didn’t match with df1)
unmatched_df2 = df2[~df2['Primary Identifier'].isin(elements_29_df['NetID'])]
unmatched_df2.head()

,User Group,Last Activity Date,Job Description,Is Blocked,Full Name,Expiry Date,Primary Identifier,Job Category,Campus Name
0,Health Sci. Dept.,NaN,NaN,No,ACQUISITIONS (HEALTH SCIENCES TEM,12/31/2382,ID1306,NaN,NaN
1,Health Sci. Dept.,NaN,NaN,No,ACQUISITIONS (HEALTH SCIENCES TEM,12/31/2382,ID509,NaN,NaN
2,Health Sci. Dept.,NaN,NaN,No,ACQUISITIONS (HEALTH SCIENCES),12/31/2382,ID510,NaN,NaN
3,Health Sci. Dept.,NaN,NaN,No,ACQUISITIONS (HEALTH SCIENCES),12/31/2382,ID511,NaN,NaN
4,Health Sci. Dept.,NaN,NaN,No,ADMINISTRATION (DENTAL),12/31/2382,ID524,NaN,NaN

In [ ]:
# Step 4: Export both to an Excel file with two sheets
output_path = r"output\Alma_Galter_Users_Match\2025_06 June\2025_06-15_Alma_Galter_Users_Match_with_Elements.xlsx"
with pd.ExcelWriter(output_path, engine='xlsxwriter') as writer:
    merged_df.to_excel(writer, sheet_name='Matched Records', index=False)
    unmatched_df2.to_excel(writer, sheet_name='Unmatched Records', index=False)

print(f"Excel workbook saved to: {output_path}")